language: python
env:
  - DJANGO_VERSION=1.8.0
  - DJANGO_VERSION=1.9.0
  - DJANGO_VERSION=1.10.0
  - DJANGO_VERSION=1.11.0
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  exclude:
    - python: "3.3"
      env: "DJANGO_VERSION=1.9.0"
    - python: "3.3"
      env: "DJANGO_VERSION=1.10.0"
    - python: "3.3"
      env: "DJANGO_VERSION=1.11.0"
    - python: "3.6"
      env: "DJANGO_VERSION=1.8.0"
    - python: "3.6"
      env: "DJANGO_VERSION=1.9.0"
    - python: "3.6"
      env: "DJANGO_VERSION=1.10.0"
install:
  - pip install django~=$DJANGO_VERSION
  - pip install .
script: ./test_project/manage.py test
